project_id = "nsahnxlrievpquybovya"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
[functions.paystack]
verify_jwt = true

[[functions]]
[functions.paystack-webhook]
verify_jwt = false