// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsahnxlrievpquybovya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zYWhueGxyaWV2cHF1eWJvdnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODQ0OTIsImV4cCI6MjA1MzY2MDQ5Mn0.2yYgeauXcdhJkjt0NFvtx2S3F8NU6WyaCpZqIAQI9vY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);